baseurl = "/"
languageCode = "en-EN"
title = "Ernest - Developer Driven Orchestration!!"
theme = "hugo-creative-theme"

# Copyright
copyright = "(c) 2017 R3 Labs"


googleAnalytics = "UA-86033085-1"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "R3 Labs"
	description = "Developer Driven Orchestration - Ernest is an open source layer that lets you drive cloud infrastructure and platforms thorough a simple config file inside your application"

	# The path must be relative to the static folder
	favicon = "dog.ico"


	# Navigation
	[params.navigation]
		brand = "Ernest"

		[params.navigation.links]
			about     = "About"
            docs      = "Documentation"
			services  = "Services"
			contact   = "Contact"
			started   = "Getting Started"



	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Developer driven Orchestration"
		subtitle   = "Ernest is an open source layer that lets you drive cloud infrastructure and platforms thorough a simple config file inside your application"
		buttonText = "Ernest 2.0.0 is out now!"



	# About section
	[params.about]
		headline    = "DevOps inside your application to stop you being blocked by the slowest team"
		description = "Ernest is infrastructure and platform as code defined by developers in their applications, delivered autonomously in any cloud or in house. Ernest lets you maximise the velocity of software delivery "
		buttonText  = "Documentation"

#
  # Portfolio modals
#  [params.portfolio.modal]
#    client = "Client"
#    date = "Date"
#    category = "Category"
#    buttonText = "Close"

	# Service section
	[params.services]
		headline = ""

        [[params.services.list]]
            icon = "fa-legal"
            title = "Compliance"
            description = "Ernest has no external dependencies so you can use it to manage any compliance-affected environment"

        [[params.services.list]]
			icon = "fa-tasks"
			title = "Manage"
			description = "Reproduce and deploy to multiple clouds, ingest existing systems and elegantly support changes to running environments"

		[[params.services.list]]
            icon = "fa-users"
            title = "Collaboration"
            description = "A centralized tool designed to support complex collaboration and sharing across teams and organisations."

        [[params.services.list]]
            icon = "fa-gears"
            title = "Change"
            description = "Gracefully change running systems and perform orderly resizes much like a sysadmin might do manually"



    # Aside section
	[params.aside]
		headline = "Ernest is open source. It's hosted, developed and maintained on GitHub."

		[params.aside.button]
			text = "View the GitHub Project"
			link = "//github.com/ernestio/ernest"

	# Contact section
	[params.contact]
		headline = "Get In Touch!"
		description = "We like hearing from people! Give us a call or send us an email and we will get back to you as soon as possible!"
		address = "2 Leman Street London E1 8FA"
		email = "info@r3labs.io"

	# Google Maps section
	[params.location]
	  latitude  = "51.514851"
	  longitude = "-0.071916"
	  maps_api_key = "AIzaSyCSRrPgUA3WJZABkKBRs1fenOcDiMFzHKk"

  # footer section
  [params.footer]
    description = "Designed and built by [R3 Labs](http://www.r3labs.io/). Maintained by the [core team](https://github.com/orgs/ernestio/people) with the excellent help of our [contributors](https://github.com/ernestio/ernest/graphs/contributors). <br> Code licensed under Mozilla 2.0. You can find us on [Twitter](https://twitter.com/r3labs), [Slack](http://ernest.io/slack/) and [Google](https://groups.google.com/forum/#!forum/ernestio)"
  	address = "2 Leman Street London E1 8FA"
  	email = "info@r3labs.io"
